"""add bet_picks table

Revision ID: 03c72f4e93d0
Revises: cea70c9ce01c
Create Date: 2026-10-06 19:14:37.893456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c72f4e93d0'
down_revision: Union[str, None] = 'cea70c9ce01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('away', sa.String(), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('book', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('p_win', sa.Float(), nullable=False),
    sa.Column('p_push', sa.Float(), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=True),
    sa.Column('market_prob', sa.Float(), nullable=True),
    sa.Column('projection', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('profit_units', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'week', 'kind', 'subject', 'market', name='uq_bet_pick_line')
    )
    op.create_index(op.f('ix_bet_picks_id'), 'bet_picks', ['id'], unique=False)
    op.create_index(op.f('ix_bet_picks_recommended'), 'bet_picks', ['recommended'], unique=False)
    op.create_index(op.f('ix_bet_picks_season'), 'bet_picks', ['season'], unique=False)
    op.create_index(op.f('ix_bet_picks_status'), 'bet_picks', ['status'], unique=False)
    op.create_index(op.f('ix_bet_picks_week'), 'bet_picks', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_picks_week'), table_name='bet_picks')
    op.drop_index(op.f('ix_bet_picks_status'), table_name='bet_picks')
    op.drop_index(op.f('ix_bet_picks_season'), table_name='bet_picks')
    op.drop_index(op.f('ix_bet_picks_recommended'), table_name='bet_picks')
    op.drop_index(op.f('ix_bet_picks_id'), table_name='bet_picks')
    op.drop_table('bet_picks')
    # ### end Alembic commands ###