"""Initial database schema

Revision ID: 0b92d89d8227
Revises: 
Create Date: 2025-08-12 21:26:40.645865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b92d89d8227'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.Text(), nullable=True),
    sa.Column('perspectives_count', sa.Integer(), nullable=True),
    sa.Column('consensus_score', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=True),
    sa.Column('ai_model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('QB', 'RB', 'WR', 'TE', 'K', 'DEF', name='player_position'), nullable=False),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('yahoo_id', sa.String(), nullable=True),
    sa.Column('sleeper_id', sa.String(), nullable=True),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('depth_chart_order', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_espn_id'), 'players', ['espn_id'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_sleeper_id'), 'players', ['sleeper_id'], unique=True)
    op.create_index(op.f('ix_players_yahoo_id'), 'players', ['yahoo_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('preferred_scoring', sa.String(), nullable=True),
    sa.Column('favorite_teams', sa.JSON(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('draft_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('user_team_id', sa.String(), nullable=True),
    sa.Column('draft_settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('user_roster', sa.JSON(), nullable=True),
    sa.Column('draft_grade', sa.String(), nullable=True),
    sa.Column('final_analysis', sa.Text(), nullable=True),
    sa.Column('recommendations_used', sa.Integer(), nullable=True),
    sa.Column('ai_accuracy_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_sessions_id'), 'draft_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_draft_sessions_session_id'), 'draft_sessions', ['session_id'], unique=True)
    op.create_table('user_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('SLEEPER', 'ESPN', 'YAHOO', 'NFL', 'CBS', name='platformtype'), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('league_key', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('scoring_format', sa.String(), nullable=True),
    sa.Column('league_size', sa.Integer(), nullable=True),
    sa.Column('is_commissioner', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('enable_notifications', sa.Boolean(), nullable=True),
    sa.Column('auto_draft_assistant', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_leagues_id'), 'user_leagues', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_leagues_id'), table_name='user_leagues')
    op.drop_table('user_leagues')
    op.drop_index(op.f('ix_draft_sessions_session_id'), table_name='draft_sessions')
    op.drop_index(op.f('ix_draft_sessions_id'), table_name='draft_sessions')
    op.drop_table('draft_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_yahoo_id'), table_name='players')
    op.drop_index(op.f('ix_players_sleeper_id'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_espn_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###