"""watch_alerts

Revision ID: 239d834d4609
Revises: 5f4393f32987
Create Date: 2026-10-08 08:13:39.460190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239d834d4609'
down_revision: Union[str, None] = '5f4393f32987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Integer(), nullable=True),
    sa.Column('p_win', sa.Float(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_line', sa.Float(), nullable=True),
    sa.Column('triggered_book', sa.String(), nullable=True),
    sa.Column('triggered_price', sa.Integer(), nullable=True),
    sa.Column('triggered_units', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season', 'week', 'kind', 'subject', 'market', 'side', name='uq_watch_alert')
    )
    op.create_index(op.f('ix_watch_alerts_id'), 'watch_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_watch_alerts_status'), 'watch_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_watch_alerts_user_id'), 'watch_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_alerts_user_id'), table_name='watch_alerts')
    op.drop_index(op.f('ix_watch_alerts_status'), table_name='watch_alerts')
    op.drop_index(op.f('ix_watch_alerts_id'), table_name='watch_alerts')
    op.drop_table('watch_alerts')
    # ### end Alembic commands ###