"""enhance_player_model_with_advanced_stats

Revision ID: 3b93073ced0c
Revises: 0b92d89d8227
Create Date: 2025-08-13 04:31:55.561150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b93073ced0c'
down_revision: Union[str, None] = '0b92d89d8227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum types first
    injury_status_enum = sa.Enum('HEALTHY', 'QUESTIONABLE', 'DOUBTFUL', 'OUT', 'IR', 'PUP', 'SUSPENDED', name='injury_status')
    injury_status_enum.create(op.get_bind())
    
    risk_level_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level') 
    risk_level_enum.create(op.get_bind())
    op.add_column('players', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('height', sa.String(), nullable=True))
    op.add_column('players', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('college', sa.String(), nullable=True))
    op.add_column('players', sa.Column('years_exp', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('projected_points_half_ppr', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('projected_points_standard', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('adp_trend', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('ownership_percentage', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('target_share', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('air_yards_share', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('red_zone_targets', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('carries_share', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('snap_count_percentage', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('games_played', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('games_started', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('fantasy_points_ppr', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('fantasy_points_half_ppr', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('fantasy_points_standard', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('season_stats', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('last_game_stats', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('strength_of_schedule', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('injury_body_part', sa.String(), nullable=True))
    op.add_column('players', sa.Column('injury_notes', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('injury_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('practice_status', sa.String(), nullable=True))
    op.add_column('players', sa.Column('trending_direction', sa.String(), nullable=True))
    op.add_column('players', sa.Column('trending_count', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('news_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('players', sa.Column('latest_news', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('ceiling_score', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('floor_score', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('consistency_rating', sa.Float(), nullable=True))
    op.add_column('players', sa.Column('position_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('tier', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('expert_consensus_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('is_rookie', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('is_handcuff', sa.Boolean(), nullable=True))
    op.add_column('players', sa.Column('handcuff_to_player_id', sa.String(), nullable=True))
    # Convert existing data and change column types with proper mapping
    op.execute("ALTER TABLE players ALTER COLUMN injury_status TYPE injury_status USING CASE WHEN injury_status IS NULL THEN 'HEALTHY'::injury_status WHEN injury_status = 'Healthy' THEN 'HEALTHY'::injury_status ELSE UPPER(injury_status)::injury_status END")
    op.execute("ALTER TABLE players ALTER COLUMN risk_level TYPE risk_level USING CASE WHEN risk_level IS NULL THEN 'MEDIUM'::risk_level ELSE UPPER(risk_level)::risk_level END")
    op.create_index(op.f('ix_players_team'), 'players', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_team'), table_name='players')
    op.alter_column('players', 'risk_level',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('players', 'injury_status',
               existing_type=sa.Enum('HEALTHY', 'QUESTIONABLE', 'DOUBTFUL', 'OUT', 'IR', 'PUP', 'SUSPENDED', name='injury_status'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('players', 'handcuff_to_player_id')
    op.drop_column('players', 'is_handcuff')
    op.drop_column('players', 'is_rookie')
    op.drop_column('players', 'expert_consensus_rank')
    op.drop_column('players', 'tier')
    op.drop_column('players', 'position_rank')
    op.drop_column('players', 'consistency_rating')
    op.drop_column('players', 'floor_score')
    op.drop_column('players', 'ceiling_score')
    op.drop_column('players', 'latest_news')
    op.drop_column('players', 'news_updated_at')
    op.drop_column('players', 'trending_count')
    op.drop_column('players', 'trending_direction')
    op.drop_column('players', 'practice_status')
    op.drop_column('players', 'injury_updated_at')
    op.drop_column('players', 'injury_notes')
    op.drop_column('players', 'injury_body_part')
    op.drop_column('players', 'strength_of_schedule')
    op.drop_column('players', 'last_game_stats')
    op.drop_column('players', 'season_stats')
    op.drop_column('players', 'fantasy_points_standard')
    op.drop_column('players', 'fantasy_points_half_ppr')
    op.drop_column('players', 'fantasy_points_ppr')
    op.drop_column('players', 'games_started')
    op.drop_column('players', 'games_played')
    op.drop_column('players', 'snap_count_percentage')
    op.drop_column('players', 'carries_share')
    op.drop_column('players', 'red_zone_targets')
    op.drop_column('players', 'air_yards_share')
    op.drop_column('players', 'target_share')
    op.drop_column('players', 'ownership_percentage')
    op.drop_column('players', 'adp_trend')
    op.drop_column('players', 'projected_points_standard')
    op.drop_column('players', 'projected_points_half_ppr')
    op.drop_column('players', 'jersey_number')
    op.drop_column('players', 'years_exp')
    op.drop_column('players', 'college')
    op.drop_column('players', 'weight')
    op.drop_column('players', 'height')
    op.drop_column('players', 'age')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    
    # Drop enum types
    sa.Enum('HEALTHY', 'QUESTIONABLE', 'DOUBTFUL', 'OUT', 'IR', 'PUP', 'SUSPENDED', name='injury_status').drop(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level').drop(op.get_bind())
    # ### end Alembic commands ###