"""add_real_roster_and_scoring_settings_to_user_leagues

Revision ID: 4f785f034efe
Revises: a3c1e9f4b2d7
Create Date: 2026-08-22 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f785f034efe'
down_revision: Union[str, None] = 'a3c1e9f4b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leagues', sa.Column('roster_positions', sa.Text(), nullable=True))
    op.add_column('user_leagues', sa.Column('points_per_reception', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leagues', 'points_per_reception')
    op.drop_column('user_leagues', 'roster_positions')
    # ### end Alembic commands ###
