"""engine_version on picks and entries; tracked_entries

Revision ID: 5f4393f32987
Revises: 8ab3f8bb12ed
Create Date: 2026-10-07 23:37:15.583764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4393f32987'
down_revision: Union[str, None] = '8ab3f8bb12ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('p_all', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('payouts', sa.JSON(), nullable=True),
    sa.Column('has_specials', sa.Boolean(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payout_mult', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'week', 'signature', name='uq_tracked_entry')
    )
    op.create_index(op.f('ix_tracked_entries_engine_version'), 'tracked_entries', ['engine_version'], unique=False)
    op.create_index(op.f('ix_tracked_entries_id'), 'tracked_entries', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_entries_season'), 'tracked_entries', ['season'], unique=False)
    op.create_index(op.f('ix_tracked_entries_status'), 'tracked_entries', ['status'], unique=False)
    op.create_index(op.f('ix_tracked_entries_week'), 'tracked_entries', ['week'], unique=False)
    op.add_column('bet_picks', sa.Column('engine_version', sa.String(), nullable=True))
    op.create_index(op.f('ix_bet_picks_engine_version'), 'bet_picks', ['engine_version'], unique=False)
    op.add_column('user_entries', sa.Column('engine_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_entries', 'engine_version')
    op.drop_index(op.f('ix_bet_picks_engine_version'), table_name='bet_picks')
    op.drop_column('bet_picks', 'engine_version')
    op.drop_index(op.f('ix_tracked_entries_week'), table_name='tracked_entries')
    op.drop_index(op.f('ix_tracked_entries_status'), table_name='tracked_entries')
    op.drop_index(op.f('ix_tracked_entries_season'), table_name='tracked_entries')
    op.drop_index(op.f('ix_tracked_entries_id'), table_name='tracked_entries')
    op.drop_index(op.f('ix_tracked_entries_engine_version'), table_name='tracked_entries')
    op.drop_table('tracked_entries')
    # ### end Alembic commands ###