"""bet_picks closing line

Revision ID: 84bb7a784ff5
Revises: 239d834d4609
Create Date: 2026-10-08 15:38:34.657725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bb7a784ff5'
down_revision: Union[str, None] = '239d834d4609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet_picks', sa.Column('close_line', sa.Float(), nullable=True))
    op.add_column('bet_picks', sa.Column('close_market_prob', sa.Float(), nullable=True))
    op.add_column('bet_picks', sa.Column('close_price', sa.Integer(), nullable=True))
    op.add_column('bet_picks', sa.Column('close_book', sa.String(), nullable=True))
    op.add_column('bet_picks', sa.Column('close_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet_picks', 'close_seen_at')
    op.drop_column('bet_picks', 'close_book')
    op.drop_column('bet_picks', 'close_price')
    op.drop_column('bet_picks', 'close_market_prob')
    op.drop_column('bet_picks', 'close_line')
    # ### end Alembic commands ###