"""add_espn_authentication_fields

Revision ID: 862b67a8787f
Revises: 3b93073ced0c
Create Date: 2025-08-13 21:59:06.993286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862b67a8787f'
down_revision: Union[str, None] = '3b93073ced0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leagues', sa.Column('espn_swid', sa.String(), nullable=True))
    op.add_column('user_leagues', sa.Column('espn_s2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leagues', 'espn_s2')
    op.drop_column('user_leagues', 'espn_swid')
    # ### end Alembic commands ###