"""analyst_picks

Revision ID: 8a1d317921b0
Revises: d8dfb306b6a5
Create Date: 2026-10-08 22:34:08.546216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1d317921b0'
down_revision: Union[str, None] = 'd8dfb306b6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('analyst', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('aired_on', sa.Date(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('line_stated', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('conviction', sa.String(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'aired_on', 'analyst', 'player', 'market', 'side', 'line', name='uq_analyst_pick')
    )
    op.create_index(op.f('ix_analyst_picks_id'), 'analyst_picks', ['id'], unique=False)
    op.create_index(op.f('ix_analyst_picks_season'), 'analyst_picks', ['season'], unique=False)
    op.create_index(op.f('ix_analyst_picks_source'), 'analyst_picks', ['source'], unique=False)
    op.create_index(op.f('ix_analyst_picks_sport'), 'analyst_picks', ['sport'], unique=False)
    op.create_index(op.f('ix_analyst_picks_status'), 'analyst_picks', ['status'], unique=False)
    op.create_index(op.f('ix_analyst_picks_week'), 'analyst_picks', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_picks_week'), table_name='analyst_picks')
    op.drop_index(op.f('ix_analyst_picks_status'), table_name='analyst_picks')
    op.drop_index(op.f('ix_analyst_picks_sport'), table_name='analyst_picks')
    op.drop_index(op.f('ix_analyst_picks_source'), table_name='analyst_picks')
    op.drop_index(op.f('ix_analyst_picks_season'), table_name='analyst_picks')
    op.drop_index(op.f('ix_analyst_picks_id'), table_name='analyst_picks')
    op.drop_table('analyst_picks')
    # ### end Alembic commands ###