"""add_yahoo_authentication_fields

Revision ID: 9c1a2f6b3d47
Revises: e6668d9d2d31
Create Date: 2026-08-22 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1a2f6b3d47'
down_revision: Union[str, None] = 'e6668d9d2d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leagues', sa.Column('yahoo_access_token', sa.String(), nullable=True))
    op.add_column('user_leagues', sa.Column('yahoo_refresh_token', sa.String(), nullable=True))
    op.add_column('user_leagues', sa.Column('yahoo_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leagues', 'yahoo_token_expires_at')
    op.drop_column('user_leagues', 'yahoo_refresh_token')
    op.drop_column('user_leagues', 'yahoo_access_token')
    # ### end Alembic commands ###
