"""Add nfl_schedule tables (nfl_games, nfl_teams, defensive_matchup_rankings, team_matchup_strength)

Revision ID: b1da1df1cbe7
Revises: b35a100cf963
Create Date: 2026-08-20 13:03:10.153112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1da1df1cbe7'
down_revision: Union[str, None] = 'b35a100cf963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defensive_matchup_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('rank_vs_position', sa.Integer(), nullable=False),
    sa.Column('fantasy_points_allowed_avg', sa.Float(), nullable=True),
    sa.Column('fantasy_points_allowed_last_4', sa.Float(), nullable=True),
    sa.Column('target_share_allowed', sa.Float(), nullable=True),
    sa.Column('red_zone_attempts_allowed', sa.Float(), nullable=True),
    sa.Column('pressure_rate', sa.Float(), nullable=True),
    sa.Column('matchup_rating', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defensive_matchup_rankings_id'), 'defensive_matchup_rankings', ['id'], unique=False)
    op.create_index(op.f('ix_defensive_matchup_rankings_position'), 'defensive_matchup_rankings', ['position'], unique=False)
    op.create_index(op.f('ix_defensive_matchup_rankings_team_abbreviation'), 'defensive_matchup_rankings', ['team_abbreviation'], unique=False)
    op.create_index(op.f('ix_defensive_matchup_rankings_week'), 'defensive_matchup_rankings', ['week'], unique=False)
    op.create_table('nfl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'POSTPONED', 'CANCELLED', name='gamestatus'), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('weather_conditions', sa.JSON(), nullable=True),
    sa.Column('vegas_line', sa.Float(), nullable=True),
    sa.Column('over_under', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_games_away_team'), 'nfl_games', ['away_team'], unique=False)
    op.create_index(op.f('ix_nfl_games_game_id'), 'nfl_games', ['game_id'], unique=True)
    op.create_index(op.f('ix_nfl_games_home_team'), 'nfl_games', ['home_team'], unique=False)
    op.create_index(op.f('ix_nfl_games_id'), 'nfl_games', ['id'], unique=False)
    op.create_table('nfl_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('yards_per_game', sa.Float(), nullable=True),
    sa.Column('passing_yards_per_game', sa.Float(), nullable=True),
    sa.Column('rushing_yards_per_game', sa.Float(), nullable=True),
    sa.Column('turnovers_per_game', sa.Float(), nullable=True),
    sa.Column('points_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('yards_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('passing_yards_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('rushing_yards_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('takeaways_per_game', sa.Float(), nullable=True),
    sa.Column('sacks_per_game', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_teams_abbreviation'), 'nfl_teams', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_nfl_teams_id'), 'nfl_teams', ['id'], unique=False)
    op.create_table('team_matchup_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_abbreviation', sa.String(), nullable=False),
    sa.Column('qb_production_rank', sa.Integer(), nullable=True),
    sa.Column('rb_production_rank', sa.Integer(), nullable=True),
    sa.Column('wr_production_rank', sa.Integer(), nullable=True),
    sa.Column('te_production_rank', sa.Integer(), nullable=True),
    sa.Column('red_zone_efficiency', sa.Float(), nullable=True),
    sa.Column('third_down_conversion', sa.Float(), nullable=True),
    sa.Column('pace_of_play', sa.Float(), nullable=True),
    sa.Column('passing_attack_efficiency', sa.Float(), nullable=True),
    sa.Column('rushing_attack_efficiency', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_matchup_strength_id'), 'team_matchup_strength', ['id'], unique=False)
    op.create_index(op.f('ix_team_matchup_strength_team_abbreviation'), 'team_matchup_strength', ['team_abbreviation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_matchup_strength_team_abbreviation'), table_name='team_matchup_strength')
    op.drop_index(op.f('ix_team_matchup_strength_id'), table_name='team_matchup_strength')
    op.drop_table('team_matchup_strength')
    op.drop_index(op.f('ix_nfl_teams_id'), table_name='nfl_teams')
    op.drop_index(op.f('ix_nfl_teams_abbreviation'), table_name='nfl_teams')
    op.drop_table('nfl_teams')
    op.drop_index(op.f('ix_nfl_games_id'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_home_team'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_game_id'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_away_team'), table_name='nfl_games')
    op.drop_table('nfl_games')
    op.drop_index(op.f('ix_defensive_matchup_rankings_week'), table_name='defensive_matchup_rankings')
    op.drop_index(op.f('ix_defensive_matchup_rankings_team_abbreviation'), table_name='defensive_matchup_rankings')
    op.drop_index(op.f('ix_defensive_matchup_rankings_position'), table_name='defensive_matchup_rankings')
    op.drop_index(op.f('ix_defensive_matchup_rankings_id'), table_name='defensive_matchup_rankings')
    op.drop_table('defensive_matchup_rankings')
    # ### end Alembic commands ###