"""Add league scoring configuration models

Revision ID: b35a100cf963
Revises: 469a1e42f57f
Create Date: 2025-08-31 11:38:24.407971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b35a100cf963'
down_revision: Union[str, None] = '469a1e42f57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waiver_wire_recommendations_id', table_name='waiver_wire_recommendations')
    op.drop_table('waiver_wire_recommendations')
    op.drop_index('ix_player_evaluations_id', table_name='player_evaluations')
    op.drop_table('player_evaluations')
    op.drop_index('ix_matchup_histories_id', table_name='matchup_histories')
    op.drop_index('ix_matchup_histories_season', table_name='matchup_histories')
    op.drop_index('ix_matchup_histories_team_a', table_name='matchup_histories')
    op.drop_index('ix_matchup_histories_team_b', table_name='matchup_histories')
    op.drop_index('ix_matchup_histories_week', table_name='matchup_histories')
    op.drop_table('matchup_histories')
    op.drop_index('ix_player_season_summaries_id', table_name='player_season_summaries')
    op.drop_index('ix_player_season_summaries_player_id', table_name='player_season_summaries')
    op.drop_index('ix_player_season_summaries_season', table_name='player_season_summaries')
    op.drop_table('player_season_summaries')
    op.drop_index('ix_player_historical_performance_id', table_name='player_historical_performance')
    op.drop_index('ix_player_historical_performance_player_id', table_name='player_historical_performance')
    op.drop_index('ix_player_historical_performance_season', table_name='player_historical_performance')
    op.drop_index('ix_player_historical_performance_week', table_name='player_historical_performance')
    op.drop_table('player_historical_performance')
    op.drop_index('ix_waiver_wire_trends_id', table_name='waiver_wire_trends')
    op.drop_table('waiver_wire_trends')
    op.drop_index('ix_fantasy_league_histories_id', table_name='fantasy_league_histories')
    op.drop_index('ix_fantasy_league_histories_season', table_name='fantasy_league_histories')
    op.drop_index('ix_fantasy_league_histories_user_id', table_name='fantasy_league_histories')
    op.drop_table('fantasy_league_histories')
    op.drop_index('ix_player_trends_id', table_name='player_trends')
    op.drop_index('ix_player_trends_player_id', table_name='player_trends')
    op.drop_table('player_trends')
    op.drop_index('ix_waiver_wire_alerts_id', table_name='waiver_wire_alerts')
    op.drop_table('waiver_wire_alerts')
    op.drop_index('ix_game_situations_player_id', table_name='game_situations')
    op.drop_index('ix_situational_trends_player_id', table_name='situational_trends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_situational_trends_player_id', 'situational_trends', ['player_id'], unique=False)
    op.create_index('ix_game_situations_player_id', 'game_situations', ['player_id'], unique=False)
    op.create_table('waiver_wire_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('urgency', postgresql.ENUM('urgent', 'high', 'medium', 'low', 'watch', name='priority'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('trigger_event', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ownership_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='waiver_wire_alerts_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='waiver_wire_alerts_pkey')
    )
    op.create_index('ix_waiver_wire_alerts_id', 'waiver_wire_alerts', ['id'], unique=False)
    op.create_table('player_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trend_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('trend_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('trend_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trend_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trend_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('performance_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usage_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('efficiency_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('touchdown_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('health_trend', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('team_situation_change', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('competition_change', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schedule_strength_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sustainability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('regression_likelihood', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('breakout_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_trends_pkey')
    )
    op.create_index('ix_player_trends_player_id', 'player_trends', ['player_id'], unique=False)
    op.create_index('ix_player_trends_id', 'player_trends', ['id'], unique=False)
    op.create_table('fantasy_league_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('league_platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('league_external_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('league_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('league_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scoring_format', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('regular_season_wins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('regular_season_losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playoff_finish', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points_for', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_points_against', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('regular_season_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points_for_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('efficiency_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('draft_grade', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('draft_value_generated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('best_draft_pick', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('worst_draft_pick', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('waiver_moves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trades_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('optimal_lineup_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('highest_weekly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lowest_weekly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('most_bench_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='fantasy_league_histories_pkey')
    )
    op.create_index('ix_fantasy_league_histories_user_id', 'fantasy_league_histories', ['user_id'], unique=False)
    op.create_index('ix_fantasy_league_histories_season', 'fantasy_league_histories', ['season'], unique=False)
    op.create_index('ix_fantasy_league_histories_id', 'fantasy_league_histories', ['id'], unique=False)
    op.create_table('waiver_wire_trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ownership_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pickup_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('drop_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recent_performance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upcoming_matchup_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_share_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('snap_count_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('red_zone_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='waiver_wire_trends_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='waiver_wire_trends_pkey')
    )
    op.create_index('ix_waiver_wire_trends_id', 'waiver_wire_trends', ['id'], unique=False)
    op.create_table('player_historical_performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('opponent_team', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('game_location', postgresql.ENUM('home', 'away', 'neutral', name='gamelocation'), autoincrement=False, nullable=True),
    sa.Column('weather_conditions', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('game_script', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fantasy_points_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fantasy_points_half_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fantasy_points_standard', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passing_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rushing_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('receiving_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('defensive_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('kicking_stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('snap_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('snap_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('air_yards', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('red_zone_targets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_zone_targets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('touches_when_ahead', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('touches_when_behind', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fourth_quarter_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yards_per_touch', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yards_after_contact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('drop_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('injury_designation', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('games_missed_prior', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_type', postgresql.ENUM('weekly', 'season', 'career', name='performancetype'), server_default=sa.text("'weekly'::performancetype"), autoincrement=False, nullable=False),
    sa.Column('is_playoffs', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_historical_performance_pkey')
    )
    op.create_index('ix_player_historical_performance_week', 'player_historical_performance', ['week'], unique=False)
    op.create_index('ix_player_historical_performance_season', 'player_historical_performance', ['season'], unique=False)
    op.create_index('ix_player_historical_performance_player_id', 'player_historical_performance', ['player_id'], unique=False)
    op.create_index('ix_player_historical_performance_id', 'player_historical_performance', ['id'], unique=False)
    op.create_table('player_season_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_played', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_started', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_fantasy_points_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_fantasy_points_half_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_fantasy_points_standard', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_fantasy_points_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_fantasy_points_half_ppr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_fantasy_points_standard', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_ceiling', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weekly_floor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('consistency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('boom_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bust_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_half_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('second_half_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('vs_top_defenses_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vs_bottom_defenses_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('home_game_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('away_game_avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('injury_weeks_missed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('injury_weeks_limited', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('health_grade', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('breakout_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sustainability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('position_finish', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_finish_half_season', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adp_vs_finish', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_season_summaries_pkey')
    )
    op.create_index('ix_player_season_summaries_season', 'player_season_summaries', ['season'], unique=False)
    op.create_index('ix_player_season_summaries_player_id', 'player_season_summaries', ['player_id'], unique=False)
    op.create_index('ix_player_season_summaries_id', 'player_season_summaries', ['id'], unique=False)
    op.create_table('matchup_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_a', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('team_b', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('game_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('final_score_a', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_score_b', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_script', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('qb_fantasy_allowed_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qb_fantasy_allowed_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rb_fantasy_allowed_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rb_fantasy_allowed_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wr_fantasy_allowed_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wr_fantasy_allowed_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('te_fantasy_allowed_a', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('te_fantasy_allowed_b', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weather', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wind_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precipitation', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dome_game', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='matchup_histories_pkey')
    )
    op.create_index('ix_matchup_histories_week', 'matchup_histories', ['week'], unique=False)
    op.create_index('ix_matchup_histories_team_b', 'matchup_histories', ['team_b'], unique=False)
    op.create_index('ix_matchup_histories_team_a', 'matchup_histories', ['team_a'], unique=False)
    op.create_index('ix_matchup_histories_season', 'matchup_histories', ['season'], unique=False)
    op.create_index('ix_matchup_histories_id', 'matchup_histories', ['id'], unique=False)
    op.create_table('player_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('projected_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('floor_projection', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ceiling_projection', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('target_share', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('snap_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('red_zone_opportunities', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goal_line_carries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matchup_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('opposing_defense_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_away', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('injury_report_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('weather_concerns', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('game_script_favorable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('performance_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('usage_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('efficiency_trend', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('breakout_probability', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('bust_probability', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('consistency_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='player_evaluations_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='player_evaluations_pkey')
    )
    op.create_index('ix_player_evaluations_id', 'player_evaluations', ['id'], unique=False)
    op.create_table('waiver_wire_recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recommendation_type', postgresql.ENUM('add', 'drop', 'stash', 'avoid', name='recommendationtype'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('urgent', 'high', 'medium', 'low', 'watch', name='priority'), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projected_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ownership_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend_direction', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('injury_related', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('matchup_driven', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('target_share_increase', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('volume_increase', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='waiver_wire_recommendations_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='waiver_wire_recommendations_pkey')
    )
    op.create_index('ix_waiver_wire_recommendations_id', 'waiver_wire_recommendations', ['id'], unique=False)
    # ### end Alembic commands ###