"""add_scoring_rules_to_user_leagues

Revision ID: c2d6a8f1b3e5
Revises: 4f785f034efe
Create Date: 2026-08-22 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d6a8f1b3e5'
down_revision: Union[str, None] = '4f785f034efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_leagues', sa.Column('scoring_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leagues', 'scoring_rules')
    # ### end Alembic commands ###
