"""game_weather

Revision ID: d8dfb306b6a5
Revises: 84bb7a784ff5
Create Date: 2026-10-08 17:28:26.382933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dfb306b6a5'
down_revision: Union[str, None] = '84bb7a784ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('gust_mph', sa.Float(), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('precip_prob', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'week', 'game', name='uq_game_weather')
    )
    op.create_index(op.f('ix_game_weather_id'), 'game_weather', ['id'], unique=False)
    op.create_index(op.f('ix_game_weather_season'), 'game_weather', ['season'], unique=False)
    op.create_index(op.f('ix_game_weather_week'), 'game_weather', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_weather_week'), table_name='game_weather')
    op.drop_index(op.f('ix_game_weather_season'), table_name='game_weather')
    op.drop_index(op.f('ix_game_weather_id'), table_name='game_weather')
    op.drop_table('game_weather')
    # ### end Alembic commands ###