"""Drop unused users.is_premium column

Revision ID: e6668d9d2d31
Revises: b1da1df1cbe7
Create Date: 2026-08-20 13:21:20.806856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6668d9d2d31'
down_revision: Union[str, None] = 'b1da1df1cbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###