"""Recreate league scoring, waiver wire, and historical performance tables

Revision ID: f9c3eac2171a
Revises: f97bb25185e9
Create Date: 2026-08-22 20:54:55.835627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c3eac2171a'
down_revision: Union[str, None] = 'f97bb25185e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Four enum types from this point forward (gamelocation, performancetype,
    # recommendationtype, priority) are stale orphans: they were created by
    # 7a4b2d1e5f89/df6277376539 with lowercase labels (matching each Python
    # enum's .value), then the tables that used them were dropped by
    # b35a100cf963 -- but the *types* were never dropped, so they're still
    # sitting in the database. The current models (historical_performance.py,
    # waiver_wire.py) don't use values_callable for these enums, so
    # SQLAlchemy's default behavior applies: it stores/expects the enum
    # member *name* (e.g. 'HOME', 'WEEKLY', 'ADD', 'URGENT'), not the
    # lowercase .value the orphaned types were built with. Recreating these
    # tables with the leftover lowercase types in place would either collide
    # on CREATE TYPE (if inline-created again) or silently accept the wrong
    # case and reject every real ORM insert. Drop the stale types so the
    # create_table calls below create fresh ones with labels that actually
    # match what the live models will read/write.
    op.execute("DROP TYPE IF EXISTS gamelocation")
    op.execute("DROP TYPE IF EXISTS performancetype")
    op.execute("DROP TYPE IF EXISTS recommendationtype")
    op.execute("DROP TYPE IF EXISTS priority")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchup_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.String(length=10), nullable=False),
    sa.Column('team_b', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('final_score_a', sa.Integer(), nullable=True),
    sa.Column('final_score_b', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('game_script', sa.String(length=50), nullable=True),
    sa.Column('qb_fantasy_allowed_a', sa.Float(), nullable=True),
    sa.Column('qb_fantasy_allowed_b', sa.Float(), nullable=True),
    sa.Column('rb_fantasy_allowed_a', sa.Float(), nullable=True),
    sa.Column('rb_fantasy_allowed_b', sa.Float(), nullable=True),
    sa.Column('wr_fantasy_allowed_a', sa.Float(), nullable=True),
    sa.Column('wr_fantasy_allowed_b', sa.Float(), nullable=True),
    sa.Column('te_fantasy_allowed_a', sa.Float(), nullable=True),
    sa.Column('te_fantasy_allowed_b', sa.Float(), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.String(length=50), nullable=True),
    sa.Column('dome_game', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchup_histories_id'), 'matchup_histories', ['id'], unique=False)
    op.create_index(op.f('ix_matchup_histories_season'), 'matchup_histories', ['season'], unique=False)
    op.create_index(op.f('ix_matchup_histories_team_a'), 'matchup_histories', ['team_a'], unique=False)
    op.create_index(op.f('ix_matchup_histories_team_b'), 'matchup_histories', ['team_b'], unique=False)
    op.create_index(op.f('ix_matchup_histories_week'), 'matchup_histories', ['week'], unique=False)
    op.create_table('scoring_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scoring_type', sa.Enum('PPR', 'Half_PPR', 'Standard', 'Custom', name='scoringtype'), nullable=False),
    sa.Column('scoring_settings', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('created_by_platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_scoring_presets_id'), 'scoring_presets', ['id'], unique=False)
    op.create_table('fantasy_league_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('league_platform', sa.String(length=20), nullable=False),
    sa.Column('league_external_id', sa.String(length=100), nullable=False),
    sa.Column('league_name', sa.String(length=200), nullable=True),
    sa.Column('league_size', sa.Integer(), nullable=True),
    sa.Column('scoring_format', sa.String(length=20), nullable=True),
    sa.Column('regular_season_wins', sa.Integer(), nullable=True),
    sa.Column('regular_season_losses', sa.Integer(), nullable=True),
    sa.Column('playoff_finish', sa.Integer(), nullable=True),
    sa.Column('total_points_for', sa.Float(), nullable=True),
    sa.Column('total_points_against', sa.Float(), nullable=True),
    sa.Column('regular_season_rank', sa.Integer(), nullable=True),
    sa.Column('points_for_rank', sa.Integer(), nullable=True),
    sa.Column('efficiency_rank', sa.Integer(), nullable=True),
    sa.Column('draft_grade', sa.String(length=2), nullable=True),
    sa.Column('draft_value_generated', sa.Float(), nullable=True),
    sa.Column('best_draft_pick', sa.String(length=100), nullable=True),
    sa.Column('worst_draft_pick', sa.String(length=100), nullable=True),
    sa.Column('waiver_moves', sa.Integer(), nullable=True),
    sa.Column('trades_made', sa.Integer(), nullable=True),
    sa.Column('optimal_lineup_percentage', sa.Float(), nullable=True),
    sa.Column('highest_weekly_score', sa.Float(), nullable=True),
    sa.Column('lowest_weekly_score', sa.Float(), nullable=True),
    sa.Column('most_bench_points', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_league_histories_id'), 'fantasy_league_histories', ['id'], unique=False)
    op.create_index(op.f('ix_fantasy_league_histories_season'), 'fantasy_league_histories', ['season'], unique=False)
    op.create_index(op.f('ix_fantasy_league_histories_user_id'), 'fantasy_league_histories', ['user_id'], unique=False)
    op.create_table('player_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=False),
    sa.Column('floor_projection', sa.Float(), nullable=False),
    sa.Column('ceiling_projection', sa.Float(), nullable=False),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('snap_percentage', sa.Float(), nullable=True),
    sa.Column('red_zone_opportunities', sa.Integer(), nullable=True),
    sa.Column('goal_line_carries', sa.Integer(), nullable=True),
    sa.Column('matchup_rating', sa.Float(), nullable=True),
    sa.Column('opposing_defense_rank', sa.Integer(), nullable=True),
    sa.Column('home_away', sa.String(length=4), nullable=True),
    sa.Column('injury_report_status', sa.String(length=20), nullable=True),
    sa.Column('weather_concerns', sa.Boolean(), nullable=True),
    sa.Column('game_script_favorable', sa.Boolean(), nullable=True),
    sa.Column('performance_trend', sa.Float(), nullable=True),
    sa.Column('usage_trend', sa.Float(), nullable=True),
    sa.Column('efficiency_trend', sa.Float(), nullable=True),
    sa.Column('breakout_probability', sa.Float(), nullable=True),
    sa.Column('bust_probability', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_evaluations_id'), 'player_evaluations', ['id'], unique=False)
    op.create_table('player_historical_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('opponent_team', sa.String(length=10), nullable=True),
    sa.Column('game_location', sa.Enum('HOME', 'AWAY', 'NEUTRAL', name='gamelocation'), nullable=True),
    sa.Column('weather_conditions', sa.String(length=100), nullable=True),
    sa.Column('game_script', sa.String(length=50), nullable=True),
    sa.Column('fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_half_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_points_standard', sa.Float(), nullable=True),
    sa.Column('passing_stats', sa.JSON(), nullable=True),
    sa.Column('rushing_stats', sa.JSON(), nullable=True),
    sa.Column('receiving_stats', sa.JSON(), nullable=True),
    sa.Column('defensive_stats', sa.JSON(), nullable=True),
    sa.Column('kicking_stats', sa.JSON(), nullable=True),
    sa.Column('snap_count', sa.Integer(), nullable=True),
    sa.Column('snap_percentage', sa.Float(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('air_yards', sa.Float(), nullable=True),
    sa.Column('red_zone_targets', sa.Integer(), nullable=True),
    sa.Column('end_zone_targets', sa.Integer(), nullable=True),
    sa.Column('touches_when_ahead', sa.Integer(), nullable=True),
    sa.Column('touches_when_behind', sa.Integer(), nullable=True),
    sa.Column('fourth_quarter_usage', sa.Float(), nullable=True),
    sa.Column('yards_per_touch', sa.Float(), nullable=True),
    sa.Column('yards_after_contact', sa.Float(), nullable=True),
    sa.Column('drop_rate', sa.Float(), nullable=True),
    sa.Column('injury_designation', sa.String(length=20), nullable=True),
    sa.Column('games_missed_prior', sa.Integer(), nullable=True),
    sa.Column('performance_type', sa.Enum('WEEKLY', 'SEASON', 'CAREER', name='performancetype'), nullable=False),
    sa.Column('is_playoffs', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_historical_performance_id'), 'player_historical_performance', ['id'], unique=False)
    op.create_index(op.f('ix_player_historical_performance_player_id'), 'player_historical_performance', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_historical_performance_season'), 'player_historical_performance', ['season'], unique=False)
    op.create_index(op.f('ix_player_historical_performance_week'), 'player_historical_performance', ['week'], unique=False)
    op.create_table('player_season_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('total_fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('total_fantasy_points_half_ppr', sa.Float(), nullable=True),
    sa.Column('total_fantasy_points_standard', sa.Float(), nullable=True),
    sa.Column('avg_fantasy_points_ppr', sa.Float(), nullable=True),
    sa.Column('avg_fantasy_points_half_ppr', sa.Float(), nullable=True),
    sa.Column('avg_fantasy_points_standard', sa.Float(), nullable=True),
    sa.Column('weekly_ceiling', sa.Float(), nullable=True),
    sa.Column('weekly_floor', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('boom_weeks', sa.Integer(), nullable=True),
    sa.Column('bust_weeks', sa.Integer(), nullable=True),
    sa.Column('first_half_avg', sa.Float(), nullable=True),
    sa.Column('second_half_avg', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('vs_top_defenses_avg', sa.Float(), nullable=True),
    sa.Column('vs_bottom_defenses_avg', sa.Float(), nullable=True),
    sa.Column('home_game_avg', sa.Float(), nullable=True),
    sa.Column('away_game_avg', sa.Float(), nullable=True),
    sa.Column('injury_weeks_missed', sa.Integer(), nullable=True),
    sa.Column('injury_weeks_limited', sa.Integer(), nullable=True),
    sa.Column('health_grade', sa.String(length=2), nullable=True),
    sa.Column('breakout_score', sa.Float(), nullable=True),
    sa.Column('sustainability_score', sa.Float(), nullable=True),
    sa.Column('position_finish', sa.Integer(), nullable=True),
    sa.Column('position_finish_half_season', sa.Integer(), nullable=True),
    sa.Column('adp_vs_finish', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_season_summaries_id'), 'player_season_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_player_season_summaries_player_id'), 'player_season_summaries', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_summaries_season'), 'player_season_summaries', ['season'], unique=False)
    op.create_table('player_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('trend_start_date', sa.DateTime(), nullable=False),
    sa.Column('trend_end_date', sa.DateTime(), nullable=False),
    sa.Column('trend_type', sa.String(length=50), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('performance_change', sa.Float(), nullable=True),
    sa.Column('usage_trend', sa.Float(), nullable=True),
    sa.Column('efficiency_trend', sa.Float(), nullable=True),
    sa.Column('touchdown_trend', sa.Float(), nullable=True),
    sa.Column('health_trend', sa.String(length=20), nullable=True),
    sa.Column('team_situation_change', sa.Text(), nullable=True),
    sa.Column('competition_change', sa.Text(), nullable=True),
    sa.Column('schedule_strength_change', sa.Float(), nullable=True),
    sa.Column('sustainability_score', sa.Float(), nullable=True),
    sa.Column('regression_likelihood', sa.Float(), nullable=True),
    sa.Column('breakout_probability', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_trends_id'), 'player_trends', ['id'], unique=False)
    op.create_index(op.f('ix_player_trends_player_id'), 'player_trends', ['player_id'], unique=False)
    op.create_table('waiver_wire_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', 'WATCH', name='priority'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=True),
    sa.Column('ownership_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_wire_alerts_id'), 'waiver_wire_alerts', ['id'], unique=False)
    op.create_table('waiver_wire_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.Enum('ADD', 'DROP', 'STASH', 'AVOID', name='recommendationtype'), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', 'WATCH', name='priority'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('projected_points', sa.Float(), nullable=True),
    sa.Column('ownership_percentage', sa.Float(), nullable=True),
    sa.Column('trend_direction', sa.String(length=10), nullable=True),
    sa.Column('injury_related', sa.Boolean(), nullable=True),
    sa.Column('matchup_driven', sa.Boolean(), nullable=True),
    sa.Column('target_share_increase', sa.Boolean(), nullable=True),
    sa.Column('volume_increase', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_wire_recommendations_id'), 'waiver_wire_recommendations', ['id'], unique=False)
    op.create_table('waiver_wire_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('ownership_change', sa.Float(), nullable=False),
    sa.Column('pickup_rate', sa.Float(), nullable=False),
    sa.Column('drop_rate', sa.Float(), nullable=False),
    sa.Column('recent_performance', sa.Float(), nullable=True),
    sa.Column('upcoming_matchup_rating', sa.Float(), nullable=True),
    sa.Column('target_share_trend', sa.Float(), nullable=True),
    sa.Column('snap_count_trend', sa.Float(), nullable=True),
    sa.Column('red_zone_trend', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_wire_trends_id'), 'waiver_wire_trends', ['id'], unique=False)
    op.create_table('league_scoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_league_id', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sa.Enum('PPR', 'Half_PPR', 'Standard', 'Custom', name='scoringtype'), nullable=False),
    sa.Column('passing_yards_per_point', sa.Float(), nullable=True),
    sa.Column('passing_td_points', sa.Float(), nullable=True),
    sa.Column('passing_int_points', sa.Float(), nullable=True),
    sa.Column('passing_2pt_points', sa.Float(), nullable=True),
    sa.Column('passing_300_yard_bonus', sa.Float(), nullable=True),
    sa.Column('passing_400_yard_bonus', sa.Float(), nullable=True),
    sa.Column('passing_40_yard_td_bonus', sa.Float(), nullable=True),
    sa.Column('rushing_yards_per_point', sa.Float(), nullable=True),
    sa.Column('rushing_td_points', sa.Float(), nullable=True),
    sa.Column('rushing_2pt_points', sa.Float(), nullable=True),
    sa.Column('rushing_100_yard_bonus', sa.Float(), nullable=True),
    sa.Column('rushing_200_yard_bonus', sa.Float(), nullable=True),
    sa.Column('rushing_40_yard_td_bonus', sa.Float(), nullable=True),
    sa.Column('receiving_yards_per_point', sa.Float(), nullable=True),
    sa.Column('receiving_td_points', sa.Float(), nullable=True),
    sa.Column('receiving_2pt_points', sa.Float(), nullable=True),
    sa.Column('reception_points', sa.Float(), nullable=True),
    sa.Column('receiving_100_yard_bonus', sa.Float(), nullable=True),
    sa.Column('receiving_200_yard_bonus', sa.Float(), nullable=True),
    sa.Column('receiving_40_yard_td_bonus', sa.Float(), nullable=True),
    sa.Column('fg_0_39_points', sa.Float(), nullable=True),
    sa.Column('fg_40_49_points', sa.Float(), nullable=True),
    sa.Column('fg_50_plus_points', sa.Float(), nullable=True),
    sa.Column('fg_miss_points', sa.Float(), nullable=True),
    sa.Column('extra_point_points', sa.Float(), nullable=True),
    sa.Column('extra_point_miss_points', sa.Float(), nullable=True),
    sa.Column('def_sack_points', sa.Float(), nullable=True),
    sa.Column('def_int_points', sa.Float(), nullable=True),
    sa.Column('def_fumble_rec_points', sa.Float(), nullable=True),
    sa.Column('def_td_points', sa.Float(), nullable=True),
    sa.Column('def_safety_points', sa.Float(), nullable=True),
    sa.Column('def_block_kick_points', sa.Float(), nullable=True),
    sa.Column('def_0_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_1_6_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_7_13_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_14_20_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_21_27_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_28_34_points_allowed', sa.Float(), nullable=True),
    sa.Column('def_35_plus_points_allowed', sa.Float(), nullable=True),
    sa.Column('fumble_lost_points', sa.Float(), nullable=True),
    sa.Column('target_points', sa.Float(), nullable=True),
    sa.Column('carry_points', sa.Float(), nullable=True),
    sa.Column('completion_points', sa.Float(), nullable=True),
    sa.Column('incompletion_points', sa.Float(), nullable=True),
    sa.Column('custom_scoring_rules', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_league_id'], ['user_leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_league_id')
    )
    op.create_index(op.f('ix_league_scoring_id'), 'league_scoring', ['id'], unique=False)
    op.create_table('player_scoring_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_scoring_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('raw_stats', sa.JSON(), nullable=True),
    sa.Column('calculated_points', sa.Float(), nullable=False),
    sa.Column('points_breakdown', sa.JSON(), nullable=True),
    sa.Column('ppr_difference', sa.Float(), nullable=True),
    sa.Column('standard_difference', sa.Float(), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_scoring_id'], ['league_scoring.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_scoring_calculations_id'), 'player_scoring_calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_scoring_calculations_id'), table_name='player_scoring_calculations')
    op.drop_table('player_scoring_calculations')
    op.drop_index(op.f('ix_league_scoring_id'), table_name='league_scoring')
    op.drop_table('league_scoring')
    op.drop_index(op.f('ix_waiver_wire_trends_id'), table_name='waiver_wire_trends')
    op.drop_table('waiver_wire_trends')
    op.drop_index(op.f('ix_waiver_wire_recommendations_id'), table_name='waiver_wire_recommendations')
    op.drop_table('waiver_wire_recommendations')
    op.drop_index(op.f('ix_waiver_wire_alerts_id'), table_name='waiver_wire_alerts')
    op.drop_table('waiver_wire_alerts')
    op.drop_index(op.f('ix_player_trends_player_id'), table_name='player_trends')
    op.drop_index(op.f('ix_player_trends_id'), table_name='player_trends')
    op.drop_table('player_trends')
    op.drop_index(op.f('ix_player_season_summaries_season'), table_name='player_season_summaries')
    op.drop_index(op.f('ix_player_season_summaries_player_id'), table_name='player_season_summaries')
    op.drop_index(op.f('ix_player_season_summaries_id'), table_name='player_season_summaries')
    op.drop_table('player_season_summaries')
    op.drop_index(op.f('ix_player_historical_performance_week'), table_name='player_historical_performance')
    op.drop_index(op.f('ix_player_historical_performance_season'), table_name='player_historical_performance')
    op.drop_index(op.f('ix_player_historical_performance_player_id'), table_name='player_historical_performance')
    op.drop_index(op.f('ix_player_historical_performance_id'), table_name='player_historical_performance')
    op.drop_table('player_historical_performance')
    op.drop_index(op.f('ix_player_evaluations_id'), table_name='player_evaluations')
    op.drop_table('player_evaluations')
    op.drop_index(op.f('ix_fantasy_league_histories_user_id'), table_name='fantasy_league_histories')
    op.drop_index(op.f('ix_fantasy_league_histories_season'), table_name='fantasy_league_histories')
    op.drop_index(op.f('ix_fantasy_league_histories_id'), table_name='fantasy_league_histories')
    op.drop_table('fantasy_league_histories')
    op.drop_index(op.f('ix_scoring_presets_id'), table_name='scoring_presets')
    op.drop_table('scoring_presets')
    op.drop_index(op.f('ix_matchup_histories_week'), table_name='matchup_histories')
    op.drop_index(op.f('ix_matchup_histories_team_b'), table_name='matchup_histories')
    op.drop_index(op.f('ix_matchup_histories_team_a'), table_name='matchup_histories')
    op.drop_index(op.f('ix_matchup_histories_season'), table_name='matchup_histories')
    op.drop_index(op.f('ix_matchup_histories_id'), table_name='matchup_histories')
    op.drop_table('matchup_histories')
    # ### end Alembic commands ###